version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=krautundrueben
      - MYSQL_ROOT_PASSWORD=krautundrueben
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      # - ./sql/00_sql_dump_database_create.sql:/docker-entrypoint-initdb.d/00_sql_dump_database_create.sql
      # - ./sql/01_krautundruebenload.sql:/docker-entrypoint-initdb.d/01_krautundruebenload.sql
      # - ./sql/02_creation_tables.sql:/docker-entrypoint-initdb.d/02_creation_tables.sql
      # - ./sql/03_fill_tables.sql:/docker-entrypoint-initdb.d/03_fill_tables.sql
volumes:
  db:
    driver: local
