version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=krautundrueben
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF_8
    volumes:
#      - ./mysql:/var/lib/mysql
      - ../sql/dump:/docker-entrypoint-initdb.d
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
