-- Rezepte
CREATE TABLE REZEPT (
    REZEPTNUMMER       			INTEGER NOT NULL,
    REZEPTNAME      			VARCHAR(50)
);

CREATE TABLE REF_REZEPT (
	REF_REZEPT_ID				INTEGER NOT NULL,
	REF_ZUTAT_ZUTATENNR			INTEGER NOT NULL
);


ALTER TABLE REZEPT ADD PRIMARY KEY (ID);
ALTER TABLE REF_REZEPT ADD FOREIGN KEY (REF_REZEPT_ID) REFERENCES REZEPT  (ID);
ALTER TABLE REF_REZEPT ADD FOREIGN KEY (REF_ZUTAT_ZUTATENNR) REFERENCES ZUTAT  (ZUTATENNR);


-- Beschränkungen
CREATE TABLE BESCHRAENKUNG (
    ID		        			INTEGER NOT NULL,
    BESCHRAENKUNGNAME      		VARCHAR(50)
);

CREATE TABLE REF_BESCHRAENKUNG (
 	REF_BESCHRAENKUNG_ID		INTEGER NOT NULL,
 	REF_ZUTAT_NUTATENNR			INTEGER NOT NULL
);

ALTER TABLE BESCHRAENKUNG ADD PRIMARY KEY (ID);
ALTER TABLE REF_BESCHRAENKUNG ADD FOREIGN KEY (REF_BESCHRAENKUNG_ID) REFERENCES BESCHRAENKUNG (ID);
ALTER TABLE REF_BESCHRAENKUNG ADD FOREIGN KEY (REF_ZUTAT_NUTATENNR) REFERENCES ZUTAT  (ZUTATENNR);

-- Ernährungskategorie
CREATE TABLE ERNAEHRUNGSKATEGORIE (
    ID							INTEGER NOT NULL,
    ERNAEHRUNGSKATEGORIENAME    VARCHAR(50)
);

CREATE TABLE REF_ERNAEHRUNGSKATEGORIE (
    REF_ERNAEHRUNGSKATEGORIE_ID	INTEGER NOT NULL,
    REF_ZUTAT_NUTATENNR 		INTEGER NOT NULL
);

ALTER TABLE ERNAEHRUNGSKATEGORIE ADD PRIMARY KEY (ID);

ALTER TABLE REF_ERNAEHRUNGSKATEGORIE ADD FOREIGN KEY (REF_ERNAEHRUNGSKATEGORIE_ID) REFERENCES ERNAEHRUNGSKATEGORIE (ID);
ALTER TABLE REF_ERNAEHRUNGSKATEGORIE ADD FOREIGN KEY (REF_ZUTAT_NUTATENNR) REFERENCES ZUTAT  (ZUTATENNR);

