-- Beschränkungen
INSERT INTO BESCHRAENKUNG (ID, BESCHRAENKUNGNAME) VALUES (1001, "Laktose") ;
INSERT INTO BESCHRAENKUNG (ID, BESCHRAENKUNGNAME) VALUES (1002, "Gluten") ;
INSERT INTO BESCHRAENKUNG (ID, BESCHRAENKUNGNAME) VALUES (1003, "Nuss") ;
INSERT INTO BESCHRAENKUNG (ID, BESCHRAENKUNGNAME) VALUES (1004, "Fruktose") ;

INSERT INTO REF_BESCHRAENKUNG (REF_BESCHRAENKUNG_ID, REF_ZUTAT_NUTATENNR) VALUES (3001,1001);
INSERT INTO REF_BESCHRAENKUNG (REF_BESCHRAENKUNG_ID, REF_ZUTAT_NUTATENNR) VALUES (3002,1001);
INSERT INTO REF_BESCHRAENKUNG (REF_BESCHRAENKUNG_ID, REF_ZUTAT_NUTATENNR) VALUES (3003,1001);
INSERT INTO REF_BESCHRAENKUNG (REF_BESCHRAENKUNG_ID, REF_ZUTAT_NUTATENNR) VALUES (4001,1001);
INSERT INTO REF_BESCHRAENKUNG (REF_BESCHRAENKUNG_ID, REF_ZUTAT_NUTATENNR) VALUES (,1004);
